### ISSUE TITLE
This lib looks great and is working nice! 

### ISSUE THREAD

**Issue by Uzay-G** [geoffreylitt/simple_recommender#7]
Thank you so much for this tool. It's really useful :). I really look forward to your roadmap for the project and especially these entries:
- offline precomputation of recommendations for higher-volume datasets
- "user-item" recommendation: recommend things to a user based on all of their items

I really don't know much about this sort of complex db system so I couldn't really help, but I just wanted to thank you for this awesome package :+1:

**Comment by geoffreylitt** [comment]
Thanks! I'm curious, what are you using it for?

I'm not actively working on adding features to this at the moment, but would definitely welcome contributions.

**Comment by Uzay-G** [comment]
I used it on a social website for developers at https://www.devol.io, unfortunately it's very **hard** to build a viable community but the tool was useful.
